Toolbar and headline sections
Bleu-Yves-Sopoude/mb-portfolio pull request #2
Opened 2023-05-03 10:22 UTC by Bleu-Yves-Sopoude

In this project we :

-Added Tools bar section
-Added the headline section
-Added a working linters file for Htmll &Css
-Added a README.md based on the model of Microverse project
-Added a index.html file with first two section of Mobile portfolio based on Figma template 5
-Added a separated CSS file which position elements with Flexbox
-Added a git-ignore file which ignore node_modules/
-Used responsive values in CSS rules
-Implemented the button interactions

2023-05-03 18:27 UTC, AdnanOlarmmi requested changes
Hi @Bleu-Yves-Sopoude, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Fixed some required changes.
- Used flexbox appropriately.

## Required Changes ♻️
### I am reviewing as a second to [this](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/pull/1)
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 18:27 UTC, AdnanOlarmmi commented on index.html
> +
- [ ] Just like the previous reviewer said, kindly adjust the padding/margin to match the design, such that all the elements align exactly like the design 😃, and likewise after the alignment, the spacing should be narrow, like that of the design.

- Your design
![mobile](https://user-images.githubusercontent.com/41163571/235995445-71701431-9d2f-42a5-a5bd-a214566ec081.gif)

- Figma design
<img width="127" alt="image" src="https://user-images.githubusercontent.com/41163571/235995491-21e8b6ac-bf06-4606-ba41-6e27d7eeabca.png">

2023-05-03 18:27 UTC, AdnanOlarmmi commented on static/style.css
> +  background-image: url("/Users/mrblue/Documents/projects/mb-portfolio/static/logo.png");
- [ ] You have really attempted using the proper background, but I noticed that the image isn't showing, the problem might be from the path you used, kindly use relative path instead of absolute path. It should be something close to this.

`background-image: url("./logo.png");`
` background-image: url("./image2.png");`

![mobile](https://user-images.githubusercontent.com/41163571/236000644-0467b188-d1d5-455e-a16c-fcd1dd1a47eb.gif)

2023-05-03 18:27 UTC, AdnanOlarmmi commented on static/style.css
> +}
- [ ] I noticed that your design has two scroll bar, this is accidentally caused by the presence of the `.container` class, Kindly remove the container class and it's styles entirely and add the background image to the `.bio` class or something close, as such.

```
.bio {
  height: 718px;
  width: 100%;
  background-color: #fff;
  background-size: contain;
  background-position: center;
  padding: 100px 20px;
  background-origin: border-box;
  border-bottom-left-radius: 30%;
  background-image: url("./image2.png");
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center 30rem;
}
```
![mobile](https://user-images.githubusercontent.com/41163571/236008195-40c157fb-70f8-4a5a-af66-1b4e59f464f3.gif)

2023-05-03 18:27 UTC, AdnanOlarmmi commented on static/style.css
> +  background-image: url("/Users/mrblue/Documents/projects/mb-portfolio/static/logo.png");
- [ ] I notice that there is a bit of vertical and horizontal space around the background image, which isn't in the design, Kindly switch the background image from the logo to the header to attain a pixel perfect design as such.

```

.header {
  background-image: url("./logo.png");
  background-repeat: no-repeat;
  display: flex;
  align-items: center;
  padding: 10px 24px;
  justify-content: space-between;
  background-color: white;
  position: fixed;
  width: 100%;
}
```

![mobile](https://user-images.githubusercontent.com/41163571/236009037-b4a80fc0-95d4-42aa-b32c-d885000252a4.gif)

2023-05-03 18:27 UTC, AdnanOlarmmi commented on static/style.css
> +  background-image: url("/Users/mrblue/Documents/projects/mb-portfolio/static/logo.png");
You should be able to figure out the alignment of the bio content on your own I guess 😉

Have a nice one.

2023-05-04 10:35 UTC, roshan-bajgain approved these changes
Hi @Bleu-Yves-Sopoude, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 10:35 UTC, roshan-bajgain commented on index.html
> +            </p>
- [ ] [Optional] I would suggest you please adjust the h1 tag as it is not showing on the page. and also this is your last review so I am pointing it as optional as there is padding on the left and right please adjust it to match the Figma design
### Your design
![his](https://user-images.githubusercontent.com/81727988/236179638-4b249466-f5a3-4de8-b638-1de90baf0fbc.png)

### Figma design
![figma](https://user-images.githubusercontent.com/81727988/236179665-be6287fe-0100-48de-b1c2-ac65564ec8da.png)

2023-05-04 10:43 UTC, merged