Mobile form section
Bleu-Yves-Sopoude/mb-portfolio pull request #4
Opened 2023-05-11 17:17 UTC by Bleu-Yves-Sopoude

In this feature we:

- Added Email field
- Added Message field that accepts up to 500 chars.
- Added fields have placeholder text.
- Added name field that accepts up to 30 chars.
- Collect data by using the Formspree service
- Implemented the button interactions

2023-05-11 18:53 UTC, V-Blaze requested changes
Hi @Bleu-Yves-Sopoude  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project, that does not have a linter check, Your linters are not running properly. I'll suggest you go through your project and set up the linter properly, You can always get the linters setup process from Microverse [here](https://github.com/microverseinc/linters-config). :smile: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-12 08:36 UTC, mahbubul14 requested changes
Hi @Bleu-Yves-Sopoude,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-12 08:36 UTC, mahbubul14 commented on index.html
> +  </p>
- [ ] To improve the alignment of the get started section, it's recommended to adjust the layout of the 'Get Started' section by adding a left margin and ensuring that the font, colors, and spacing match the Figma design. :+1: 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![yourdesign](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/assets/70483835/e6abdb56-fec3-4308-8cc3-48d2ac4b6ecc) | ![Figma](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/assets/70483835/278f851c-59c4-4a2e-8860-23c1cba8d2fe)

2023-05-12 13:26 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @Bleu-Yves-Sopoude, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- Good PR Description :+1: 
- No Linters Errors :100: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 13:26 UTC, GedeonTS commented on index.html
> +     </section>
- Good job implementing all the funtionalities, however, just as requested by your last reviewer [here](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/pull/4#discussion_r1192077778), kindly make sure your Design matches the Figma design as much as possible according to [this requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates%20in%20Figma). PLease pay close attention to margins, spaces, sizes of your placeholders and fonts (family and sizes)

**Figma Design**
![Screenshot from 2023-05-12 15-18-21](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/assets/97834160/8a7e0c49-4758-4868-9622-e1aa89f83c8a)

**Your Design**
![Screenshot from 2023-05-12 15-19-31](https://github.com/Bleu-Yves-Sopoude/mb-portfolio/assets/97834160/40a9f9b1-b4a0-475e-b9c8-81c37f54c0cd)

2023-05-12 14:42 UTC, divinecharlotte approved these changes
# Hello @Bleu-Yves-Sopoude   😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive pr👍 
- Linters are passing 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 14:44 UTC, merged